services:
  - type: web
    name: daren-aeriel-shema-task-checker
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: SECRET_KEY
        generator: secret
      - key: DATABASE_URL
        fromDatabase: default
